[package]
org = "shaan"
name = "admin_service"
version = "0.1.0"
distribution = "2201.12.7"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerinax"
name = "mongodb"
version = "2.6.0"  # Compatible with 2201.12.7; 3.0.0 might need 2201.12.10

[[dependency]]
org = "ballerinax"
name = "kafka"
version = "2.6.0"  # Match MongoDB version for consistency
