[package]
org = "user"
name = "passenger_service"
version = "0.1.0"
distribution = "2201.12.10"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerinax"
name = "mongodb"
version = "5.2.2"

[[dependency]]
org = "ballerinax"
name = "kafka"
version = "4.6.0"