[package]
org = "transport"
name = "transport_service"
version = "0.1.0"
distribution = "2201.8.0"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerinax"
name = "mongodb"
version = "5.0.0"

[[dependency]]
org = "ballerinax"
name = "kafka"
version = "3.10.2"